-- Guardian AI Alert System
-- Replaces on-the-fly /api/ai/alerts with persistent, deduplicated, tracked alerts

-- ─── ai_alerts ───────────────────────────────────────────────
-- One row per alert event generated by the Guardian worker.
-- The message column holds the AI-generated prose (or template fallback).
CREATE TABLE IF NOT EXISTS ai_alerts (
  id            BIGSERIAL     PRIMARY KEY,
  client_id     INTEGER       NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  type          TEXT          NOT NULL,   -- stale_orders | out_of_stock | low_stock | subscription_expiry | fake_order_spike | bot_disabled | delivery_gap
  severity      TEXT          NOT NULL DEFAULT 'info', -- urgent | warning | info
  message       TEXT          NOT NULL,   -- AI-generated human-readable text
  ai_logic      TEXT,                     -- why the guardian fired (internal, for debugging)
  metadata      JSONB         NOT NULL DEFAULT '{}',
  link          TEXT          NOT NULL DEFAULT '',  -- target dashboard URL
  created_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_alerts_client_created
  ON ai_alerts (client_id, created_at DESC);

-- Used for the 6-hour deduplication check
CREATE INDEX IF NOT EXISTS idx_ai_alerts_client_type_created
  ON ai_alerts (client_id, type, created_at DESC);

-- ─── alert_tracking ──────────────────────────────────────────
-- Tracks each store owner's interaction with each alert.
-- Enables: read receipts, dismissals, followed actions, and
-- future "I saved you $X" monthly summary reports.
CREATE TABLE IF NOT EXISTS alert_tracking (
  id           BIGSERIAL    PRIMARY KEY,
  alert_id     BIGINT       NOT NULL REFERENCES ai_alerts(id) ON DELETE CASCADE,
  client_id    INTEGER      NOT NULL,  -- denormalised for fast per-client queries
  status       TEXT         NOT NULL DEFAULT 'unread', -- unread | read | dismissed | followed
  action_taken TEXT,                   -- e.g. "clicked" | "paused_ad" | "restocked"
  read_at      TIMESTAMPTZ,
  acted_at     TIMESTAMPTZ,
  CONSTRAINT uq_alert_tracking UNIQUE (alert_id, client_id)
);

CREATE INDEX IF NOT EXISTS idx_alert_tracking_client_status
  ON alert_tracking (client_id, status);

-- ─── user_thresholds ─────────────────────────────────────────
-- Store owners can customise how sensitive the Guardian is.
-- Rows are seeded with defaults on first Guardian scan if missing.
CREATE TABLE IF NOT EXISTS user_thresholds (
  id          BIGSERIAL   PRIMARY KEY,
  client_id   INTEGER     NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  metric      TEXT        NOT NULL,   -- stale_pending_hours | fake_order_week | low_stock_enabled | sub_expiry_days
  value       NUMERIC     NOT NULL,
  CONSTRAINT uq_user_thresholds UNIQUE (client_id, metric)
);

CREATE INDEX IF NOT EXISTS idx_user_thresholds_client
  ON user_thresholds (client_id);
