ALTER TABLE product_economics
  ADD COLUMN IF NOT EXISTS call_center_cost DECIMAL(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS return_cost DECIMAL(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS other_costs DECIMAL(10, 2) NOT NULL DEFAULT 0;
